### ISSUE TITLE
moment.duration(): full support for `Weeks` expression

### ISSUE THREAD

**Issue by RoboSparrow** [lufzle/moment-interval#10]
Hi,
this is more of a question:

Example:

`moment.duration('P1Y2M3W')` throws currently `uncaught exception: "P1Y2M3W" is an invalid ISO 8601 duration`.

However, the `nW` expression for weeks seems to be an equal property of ISO 8601 durations
- http://en.wikipedia.org/wiki/ISO_8601#Durations

This might be not fixable, because the core  moment.duration() method doesn't support a week property. Is this why you supply already `PnW` as a kind of special case?

Hope this makes sense,
jb

**Comment by RoboSparrow** [comment]
Actually, I think I mis-read the [wikipedia](http://en.wikipedia.org/wiki/ISO_8601#Durations)

> Durations are represented by the format P[n]Y[n]M[n]DT[n]H[n]M[n]S or P[n]W

Apologies, I missed the **OR** in the statement. 

Still, https://github.com/nezasa/iso8601-js-period accepts and parses durations like `P1Y2M3W`. Do you consider this behaviour as non-conformant?

**Comment by martindanielson** [comment]
I actually think that the fix is non conformant of the specification and that if you use weeks representation of durations you either use the first format OR the last one, not a mix of both.

If we mix them, then we need to pass along some sort of setting to tell whatever framework is handling this for us in what format we want to receive back. Say you created a duration with `moment.duration(a bunch of milliseconds that matches exactly a week)` there is no way for us to tell if we should show `P1W` or `P7D`. Also, what happens if we have a duration of slightly more than a week, 8 days, and request the week format. Should it give us a float or should we just get the rounded part? I see no mention of this in the spec.

**Comment by RoboSparrow** [comment]
Thank you, this makes sense.
